use_frameworks!

target 'SugarSwiftExtension_Example' do
  pod 'SugarSwiftExtension', :path => '../'

  target 'SugarSwiftExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
